export { default as ProductItem } from './product-item/product-item';
export { default as ReviewCard } from './review-card/review-card';
export { default as ReviewForm } from './review-form/review-form';
export { default as ProductTabs} from './product-tabs/product-tabs';
export { default as FeatureTab} from './feature-tab/feature-tab';
export { default as DescriptionTab} from './description-tab/description-tab';
export { default as Slider } from './slider/slider';
export { default as ReviewFormItem} from './refiew-form-item/review-form-item';
export { default as ReviewFormRateBar } from './review-form-rate-bar/review-form-rate-bar';
export { default as ReviewFormComment} from './review-form-comment/review-form-comment';
